import type { Metadata } from "next";
import { Geist, Geist_Mono, Jockey_One } from "next/font/google";
import "./globals.css";
import Nav from "./components/nav";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

const jockeyOne = Jockey_One({
    variable: "--font-jockey-one",
    weight: "400",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} ${jockeyOne.variable} antialiased`}
            >
                <div
                    className="flex flex-col items-center"
                    style={{
                        background: `
                            radial-gradient(circle at 1px 1px, rgba(34, 34, 34, 0.10) 1px, transparent 0),
                            linear-gradient(to bottom, transparent, var(--accent))
                        `,
                        backgroundSize: "20px 20px, 100% 100%",
                    }}
                >
                    <Nav />
                    {children}
                </div>
            </body>
        </html>
    );
}
