import type { Metadata } from "next";
import { Geist, Geist_Mono, Jockey_One } from "next/font/google";
import "./globals.css";
import Nav from "./components/nav";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

const jockeyOne = Jockey_One({
    variable: "--font-jockey-one",
    weight: "400",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} ${jockeyOne.variable} antialiased`}
            >
                <div className="flex flex-col items-center bg-linear-to-b from-white via-background to-accent h-screen">
                    <Nav />
                    {children}
                </div>
            </body>
        </html>
    );
}
